// Generated by CoffeeScript 1.9.3
// file unchanged (same content as EditT3) 
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.PopupNotions = (function(superClass) {
    extend(PopupNotions, superClass);

    function PopupNotions() {
      this.addInput = bind(this.addInput, this);
      this.$popupnotion = null;
      this.notions = {};
    }

    // Create the popup when user want to create notions
    PopupNotions.prototype.create = function() {
      var $class_attributes_block, $closebutton, $create_button, $instance_attributes_block, $left, $menu, $right;
      // Left part of the popup
      $left = this.createBlock('Notions', 'div_block').attr('id', 'notions_block');
      // Right part of the popup
      $right = this.createBlock('Attributes', 'div_block').attr('id', 'attributes_block');
      
      // Block inside the right part to create class attributes
      $class_attributes_block = this.createBlock('Class attributes', 'div_block col-md-2').attr('id', 'class_attributes_block');
      // Block inside the right part to create instance attributes
      $instance_attributes_block = this.createBlock('Instance attributes', 'div_block col-md-2').attr('id', 'instance_attributes_block');
      
      // Append the previous blocks to the right part of the popup
      $right.append(this.createSideBlocks([$class_attributes_block, $instance_attributes_block], [5, 5]));
      
      // Create the first input or the left part of the popup
      // When this input will be filled, another will be automatically created
      this.createLeftNotionNameInputs($left, $right);
      
      // Menu (validate, close...)
      $create_button = this.createButton('Create', true);
      $create_button.on({
        click: (function(_this) {
          return function() {
            _this.$popupnotions.trigger('notionsCreated', [_this.notions]);
            return _this.close();
          };
        })(this)
      });
      $closebutton = this.createCloseButton();
      $menu = $('<div></div>').append([$create_button, $closebutton]);
      
      // Append the left part and the right part to our popup
      this.$popupnotions = this.createPopup([this.createTitle('Create notions')], [this.createSideBlocks([$left, $right], [4, 8])], [$menu], 'notions');
      this.applyCloseButtonEvents($closebutton, this.$popupnotions);
      
      this.$popupnotions.css({
        width: "800px"
      });
      return this.$popupnotions.on({
        close: (function(_this) {
          return function() {
            _this.$popupnotions.empty();
            return _this.notions = {};
          };
        })(this)
      });
    };

    // Show the popup to create notions
    PopupNotions.prototype.show = function() {
      return this.$popupnotions.popup('show');
    };

    // Hide the popup to create notions
    PopupNotions.prototype.close = function() {
      this.$popupnotions.popup('hide');
      this.$popupnotions.empty();
      return this.notions = {};
    };

    // Return the popupnotions object
    PopupNotions.prototype.getNode = function() {
      return this.$popupnotions;
    };

    // Create the left input (notion names) according to the left (where the inputs will be put) and the right (where the class/attribute names will be put) part of the popup and append it to the left part
    PopupNotions.prototype.createLeftNotionNameInputs = function($left, $right) {
      var $input, old_name, right_panel_hidden;
      $input = this.createInputText('input_notions');
      right_panel_hidden = true;
      old_name = null;
      
      // To add or delete a new input ?
      $input.on({
        keyup: (function(_this) {
          return function(event) {
            var $elem, $next_input;
            $elem = $(event.currentTarget);
            // Add the next input if it is not already present
            // Show the right panel if needed
            if ($elem.val().length !== 0) {
              if ($elem.next().length === 0) {
                _this.createLeftNotionNameInputs($left, $right);
              }
              if (right_panel_hidden === true) {
                _this.loadRightPanel($elem, $right);
                return right_panel_hidden = false;
              }
            // Remove the next input (if it is empty) if the actual input is empty too
            // Hide the right panel if needed
            } else {
              $next_input = $elem.next();
              if ($next_input.length !== 0 && $next_input.val().length === 0) {
                $next_input.remove();
              }
              if (right_panel_hidden === false) {
                _this.loadRightPanel(null, $right);
                return right_panel_hidden = true;
              }
            }
          };
        })(this),

        // Save the new value of the input
        blur: (function(_this) {
          return function(event) {
            return _this.saveNameNotions(old_name, $(event.currentTarget).val());
          };
        })(this),
        
        // Load the right panel and save the actual value of the input
        focus: (function(_this) {
          return function(event) {
            var $elem, ref;
            $elem = $(event.currentTarget);
            old_name = $elem.val();
            _this.loadRightPanel($elem, $right);
            return right_panel_hidden = (ref = old_name === '') != null ? ref : {
              "true": false
            };
          };
        })(this)
      });
      this.loadRightPanel($input, $right);
      return $left.append($input);
    };

    // Load the right panel according to the notion name and the right part of the popup
    PopupNotions.prototype.loadRightPanel = function($notion_name_input, $right) {
      var class_values, instance_values, name;
      // If this is a new notion name for example, create an empty right panel
      if ($notion_name_input === null) {
        $right.find('.body').empty();
        return;
      }
      name = $notion_name_input.val();

      // Get the saved class/instances values of this notion name
      if ((this.notions[name] != null)) {
        class_values = this.notions[name]["class"];
        instance_values = this.notions[name]["instance"];
      } else {
        class_values = instance_values = null;
      }
      this.createInputsClass($notion_name_input, class_values, $right.find('#class_attributes_block'));
      return this.createInputsInstance($notion_name_input, instance_values, $right.find('#instance_attributes_block'));
    };

    // Create a new input for classnames of a notion according to saved values
    // Append it to the $class_block
    // Create automatically new inputs when needed
    PopupNotions.prototype.createInputsClass = function($notion_name_input, values, $class_block) {
      var $block, $group, $name_input_class, $name_input_val, index, val;
      // Clear the class block
      $block = $class_block.find('.body');
      $block.empty();
      
      // Create the classname attribute
      $group = $('<div></div>').addClass('form-group');
      $name_input_class = this.createInputText().attr('disabled', 'disabled').val('Name');
      $name_input_val = this.createInputText().attr('disabled', 'disabled');
      
      $group.append([$name_input_class, $name_input_val]);
      $block.append($group);
      
      // Add inputs with the specified saved values
      if (values !== null) {
        for (index in values) {
          val = values[index];
          if (index !== 'name') {
            this.addInput($notion_name_input, index, val, $block, 'class', (function(_this) {
              return function(name_notion, old_key, key, val) {
                return _this.saveClassValuesNotions(name_notion, old_key, key, val);
              };
            })(this));
          }
        }
      }
      // Add a new blank input
      return this.addInput($notion_name_input, '', '', $block, 'class', (function(_this) {
        return function(name_notion, old_key, key, val) {
          return _this.saveClassValuesNotions(name_notion, old_key, key, val);
        };
      })(this));
    };

    // Same as createInputsClass
    PopupNotions.prototype.createInputsInstance = function($notion_name_input, values, $instance_block) {
      var $block, index, val;
      // Clear the instance block
      $block = $instance_block.find('.body');
      $block.empty();
     
      if (values !== null) {
        for (index in values) {
          val = values[index];
          this.addInput($notion_name_input, index, val, $block, 'attribute', (function(_this) {
            return function(name_notion, old_key, key, val) {
              return _this.saveInstanceValuesNotions(name_notion, old_key, key, val);
            };
          })(this));
        }
      }
      return this.addInput($notion_name_input, '', '', $block, 'attribute', (function(_this) {
        return function(name_notion, old_key, key, val) {
          return _this.saveInstanceValuesNotions(name_notion, old_key, key, val);
        };
      })(this));
    };

    // Save the name of the notion according to an old_name and the new_name
    PopupNotions.prototype.saveNameNotions = function(old_name, new_name) {
      if (new_name === '') {
        delete this.notions[old_name];
        return;
      }
      if (old_name !== new_name) {
        // Get the class/instance attributes of the object
        this.notions[new_name] = this.notions[old_name];
        // Create a new object if it was not created before
        if ((this.notions[new_name] == null) || (this.notions[new_name]["class"] == null)) {
          this.notions[new_name] = {
            'class': {
              name: ''
            },
            instance: {}
          };
        }
        // Now we can delete the old name object
        return delete this.notions[old_name];
      }
    };

    // Save class values according to the name notion, the old_key, new_key and the value of the class attribute
    PopupNotions.prototype.saveClassValuesNotions = function(name, old_key, new_key, val) {
      if (name === '') {
        return;
      }
      if (old_key !== new_key) {
        delete this.notions[name]['class'][old_key];
      }
      if (new_key !== '') {
        return this.notions[name]['class'][new_key] = val;
      }
    };

    // Same as saveClassValuesNotions
    PopupNotions.prototype.saveInstanceValuesNotions = function(name, old_key, new_key, val) {
      if (name === '') {
        return;
      }
      if (old_key !== new_key) {
        delete this.notions[name]['instance'][old_key];
      }
      if (new_key !== '') {
        return this.notions[name]['instance'][new_key] = val;
      }
    };

    PopupNotions.prototype.addInput = function($notion_name_input, key, val, $block, class_prefix, save_callback) {
      var $element, $group, $input_key, $input_val, i, len, name, old_key, ref;
      name = $notion_name_input.val();
      $notion_name_input.on({
        // Add new input if needed
        keyup: function(event) {
          return name = $(event.currentTarget).val();
        }
      });
      $group = $('<div></div>').addClass('form-group');
      $input_key = this.createInputText(class_prefix + "_key").attr('placeholder', 'key').val(key);
      $input_val = this.createInputText(class_prefix + "_val").attr('placeholder', 'value1/value2/...').val(val);
      old_key = key;
      $input_key.on({
        keyup: (function(_this) {
          return function(event) {
            var $elem, $next_group;
            $elem = $(event.currentTarget);
            // Add the next input if it is not already present
            if ($elem.val().length !== 0) {
              if ($elem.parent().next().length === 0) {
                return _this.addInput($notion_name_input, '', '', $block, class_prefix, save_callback);
              }
            // Remove the next next (because the first next is the input value) input (if it is empty) if the actual input is empty too
            } else {
              $next_group = $elem.parent().next();
              if ($next_group.length !== 0 && $next_group.find("." + class_prefix + "_key").val().length === 0) {
                return $next_group.remove();
              }
            }
          };
        })(this)
      });
      ref = [$input_key, $input_val];
      for (i = 0, len = ref.length; i < len; i++) {
        $element = ref[i];
        $element.on({          
          // Save the key/val
          blur: (function(_this) {
            return function(event) {
              var $elem;
              $elem = $(event.currentTarget);
              //key, val
              if ($elem.hasClass(class_prefix + "_key")) {
                key = $elem.val();
                val = $elem.next().val();
              } else if ($elem.hasClass(class_prefix + "_val")) {
                val = $elem.val();
                key = $elem.prev().val();
              }
              return save_callback(name, old_key, key, val);
            };
          })(this),
          // Load the right panel
          focus: (function(_this) {
            return function(event) {
              var $elem;
              $elem = $(event.currentTarget);
              if ($elem.hasClass(class_prefix + "_key")) {
                return old_key = $elem.val();
              } else if ($elem.hasClass(class_prefix + "_val")) {
                return old_key = $elem.prev().val();
              }
            };
          })(this)
        });
      }
      $group.append([$input_key, $input_val]);
      return $block.append($group);
    };

    return PopupNotions;

  })(Popup);

}).call(this);
