// Generated by CoffeeScript 1.9.3
//TODO : Add commentaries
(function() {
  var slice = [].slice;

  window.Utils = (function() {
    function Utils() {}

    Utils.copyHash = function(hash) {
      var i, k, len, new_hash;
      new_hash = {};
      for (i = 0, len = hash.length; i < len; i++) {
        k = hash[i];
        new_hash[k] = hash[k];
      }
      return new_hash;
    };

    Utils.mouseTableUp = function(table) {
      return setTimeout((function(_this) {
        return function() {
          return table.setMouseDown(false);
        };
      })(this), 50);
    };

    Utils.merge = function() {
      var hash, hash_final, hashs, i, key, len, value;
      hashs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      hash_final = {};
      for (i = 0, len = hashs.length; i < len; i++) {
        hash = hashs[i];
        for (key in hash) {
          value = hash[key];
          hash_final[key] = value;
        }
      }
      return hash_final;
    };

    Utils.hashEqual = function(hash1, hash2) {
      var key, value;
      for (key in hash1) {
        value = hash1[key];
        if (!((hash2[key] != null) && hash2[key] === value)) {
          return false;
        }
      }
      return true;
    };

    return Utils;

  })();

}).call(this);
